name: Deploy to K8s

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/my-app:${{ github.ref }}
        env:
          DOCKER_USERNAME: ${{ github.repository_owner }}
          DOCKER_PASSWORD: ${{ secrets.PAT }}
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
  deploy:
    name: deploy
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout files
      uses: actions/checkout@v2

    - name: Set context from Kubeconfig
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG }}
        context: huytest
      id: setcontext

    - name: Get tag name
      uses: olegtarasov/get-tag@v2

    - name: Get new container image tag
      id: image-tag
      run: |
        echo "::set-output name=image::ghcr.io/tienhuy1801/my-app:$GIT_TAG_NAME"

    - name: Deploy to K8s
      uses: Azure/k8s-deploy@v1
      with:
        manifest: |
          demo.yaml
        images: |
          ${{ steps.image-tag.outputs.image }}
